### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by bnauta** [hlascelles/que-scheduler#126]
I'm having trouble installing this gem when following the instructions in the readme; hoping I can get some support.

**Gemfile**
```ruby
gem "que", "~> 1.0.0.beta3"
gem "que-scheduler", "3.2.7"
```
**config/que_schedule.yml**
```yaml
puts_job:
  cron: "* * * * *"
  class: PutsJob
  queue: default
  priority: 25
  args: ['hello!']
```

**migration**
```ruby
class CreateQueSchedulerSchema < ActiveRecord::Migration[5.2]
  def change
    Que::Scheduler::Migrations.migrate!(version: 4)
  end
end
```

Attempting to run this migration yields:
```shell
RuntimeError: The que-scheduler db migration state was found to be 0. It should be 4.
...
```

I've tried several versions of this gem, as well as both 0.14.3 and 1.0.0.beta3 versions of que. Running the migration _as_ a migration or in the console yields the same error. Am I missing something? Thanks in advance.
