### ISSUE TITLE
Scheduled jobs not running or appearing in que_scheduler_audit_enqueued table

### ISSUE THREAD

**Issue by i2chris** [hlascelles/que-scheduler#160]
Hi

I have que running and a job setup that should run every minute, but it does not run and there is nothing placed in any of the que schedule tables, including que_scheduler_audit_enqueued.

Perhaps I am doing something obviously wrong here?

Here is config/que_schedule.yml

```
working:
  cron: "*/1 * * * *"
  class: "::Mrls::Jobs::UpdateMrlsJob"
  queue: "default"
  priority: 1
```

Here is the output of the schedule in the rails console

```
2.6.3 :001 > Que::Scheduler.schedule
 => {"working"=>#<Que::Scheduler::DefinedJob cron=#<Fugit::Cron:0x0000562955f0ebd0 @original="*/1 * * * *", @cron_s=nil, @seconds=[0], @minutes=nil, @hours=nil, @monthdays=nil, @months=nil, @weekdays=nil, @zone=nil, @timezone=nil> job_class=Mrls::Jobs::UpdateMrlsJob name="working" priority=10 queue="default" schedule_type=:default>}
```

Any ideas? Thanks
